### ISSUE TITLE
Validation Error: "AttributeError: 'NightEdgeSegmentation' object has no attribute 'multiscale'"

### ISSUE THREAD

**Issue by DucTriCE** [wangsen99/FDLNet#10]
When training, in validation step, i got this error
Traceback (most recent call last):
File "train_edge.py", line 506, in
trainer.train_edge()
File "train_edge.py", line 316, in train_edge
mIoU = self.ms_val(iteration)
File "train_edge.py", line 375, in ms_val
for i, batch_data in enumerate(tqdm(self.val_loader, ascii= True)):
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/tqdm/std.py", line 1181, in iter
for obj in iterable:
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in next
data = self._next_data()
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
return self._process_data(data)
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
data.reraise()
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
data = fetcher.fetch(index)
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/mmlab/huycq/FDLNet/core/data/dataloader/night_edge.py", line 100, in getitem
output = self._val_ms_transform(img, mask)
File "/home/mmlab/huycq/FDLNet/core/data/dataloader/segbase.py", line 132, in _val_ms_transform
for scale in self.multiscale:
AttributeError: 'NightEdgeSegmentation' object has no attribute 'multiscale'
I don't see any attribute called multiscale, can you check it for me, thanks

**Comment by DucTriCE** [comment]
I found that in the paper the multiscale are [0.5, 0.75, 1.0, 1.25, 1.5, 1.75], maybe the codes missing those values ?

**Comment by wangsen99** [comment]
Sorry for the confusion, I forgot to add this in the code. By the way, you can run the eval.py or train_edge.py with "mode="val"" , since multiscale inference is time-consuming.
