### ISSUE TITLE
Problem with Dataset

### ISSUE THREAD

**Issue by DucTriCE** [wangsen99/FDLNet#9]
The datasets including in your code are BDD100K-night, NightCity and NightCity+. And the code FDLNet/core/data/dataloader/__init__.py has two only:
datasets = {
    'night': NightEdgeSegmentation,
    'citys': CitySegmentation,
}

So I want to ask which one is the NightCity, or I have to add the NightCity in as I've seen there's a script called nightcity.py in FDLNet/core/data/dataloader

**Comment by DucTriCE** [comment]
and also in training process, in NightCity, the label folder has the following branch:
(Root) Night-City-label
____color
|________train
|________val
|____label
|________train
|________val

And u guys are using the label folder for the masks, may I ask why not using color to train, as the label folder are just grayscale images

**Comment by wangsen99** [comment]
Hi, for the first question, NightEdgeSegmentation includes NightCity and its edge map as we train our model with edge loss in the paper, you can use the nightcity.py to train the model without edge loss. 
For the second, it seems like you are new to semantic segmentation, the color images are only for visualization, and the labels record the object classes by values like 1,2,3,..., which are used to train.

**Comment by DucTriCE** [comment]
Ah i got it, thanks very much !

**Comment by DucTriCE** [comment]
When training, in validation step, i got this error
Traceback (most recent call last):
  File "train_edge.py", line 506, in <module>
    trainer.train_edge()
  File "train_edge.py", line 316, in train_edge
    mIoU = self.ms_val(iteration)
  File "train_edge.py", line 375, in ms_val
    for i, batch_data in enumerate(tqdm(self.val_loader, ascii= True)):
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmlab/miniconda3/envs/fdlnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmlab/huycq/FDLNet/core/data/dataloader/night_edge.py", line 100, in __getitem__
    output = self._val_ms_transform(img, mask)
  File "/home/mmlab/huycq/FDLNet/core/data/dataloader/segbase.py", line 132, in _val_ms_transform
    for scale in self.multiscale:
AttributeError: 'NightEdgeSegmentation' object has no attribute 'multiscale'
I don't see any attribute called multiscale, can you check it for me, thanks
